### ISSUE TITLE
install pyhsmm plugins

### ISSUE THREAD

**Issue by andrwz** [mattjj/pyhsmm-slds#1]
Dear Matthew,

  first of all thanks a lot for sharing your code !

I am eager to try it out on my research project, but I find some difficulties in installing the plugins (auto-regressive, switching linear dynamical systems and factorial models).
I am using pyhton 2.7 on a windows 7 system with anaconda.

Following the other posts I could install pyhsmm and pybasicbayes.
I was wondering if there is a particular procedure I should follow for installing the plugins.
I tried to run "python setup.py install" but I keep getting the following error message:
"autoregressive\messages.h:1:22: fatal error: Eigen/Core: No such file or directory "
See full trace below:

 C:\Users\Documents\python\pyhsmm\pyhsmm\plugins\pyhsmm-autoregressive-master>python setup.py install            C:\Users\Anaconda\envs\mscenv01\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'      warnings.warn(msg)                                                                                                                running install                                                                                                                     running build                                                                                                                       running build_ext                                                                                                                   building 'autoregressive.messages' extension                                                                                        C:\TDM-GCC-64\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -IC:\Users\Anaconda\envs\mscenv01\lib\site-packages\numpy\core\include -IC:\Users\Anaconda\envs\mscenv01\lib\site-packages\pyhsmm\deps\Eigen3 -IC:\Users\Anaconda\envs\mscenv01\lib\site-packages\pyhsmm\internals -IC:\Users\Anaconda\envs\mscenv01\include -IC:\Users\Anaconda\envs\mscenv01\PC -c autoregressive\messages.cpp -o build\temp.win-amd64-2.7\Release\autoregressive\messages.o -O3 -fopenmp -std=c++11 -DEIGEN_NO_MALLOC -w -DNDEBUG                                                                                                                               In file included from autoregressive\messages.cpp:279:0:                                                                            autoregressive\messages.h:1:22: fatal error: Eigen/Core: No such file or directory                                                  compilation terminated.                                                                                                             error: command 'C:\TDM-GCC-64\bin\gcc.exe' failed with exit status 1

**Comment by mattjj** [comment]
You don't actually need to build anything in the autoregressive package; that low-level code is all optional, and everything should work very efficiently without it as long as you have pyhsmm stuff compiled.

I'll edit the setup.py file so it doesn't try to compile things by default.

If you want to be able to compile the autoregressive code anyway, read on!

It looks like the Eigen include directory is being passed in as  `-IC:\Users\Anaconda\envs\mscenv01\lib\site-packages\pyhsmm\deps\Eigen3`. Can you check whether that directory exists and contains Eigen?

My current guess is that Eigen won't be there because the pyhsmm package install (via pip or setup.py) may not include it. If that's the case, two solutions might be:
1. clone pyhsmm from github, add the repository directory to your Python path (before Anaconda's site-packages), and then try building autoregressive again
2. install Eigen somewhere on your compiler's CPLUS_INCLUDE_PATH or include its path manually with `-I`, and then try building autoregressive again

**Comment by mattjj** [comment]
I pushed a new commit to pyhsmm-autoregressive in which the setup.py file won't try to compile stuff anymore. Give that a shot.

**Comment by andrwz** [comment]
Dear Matthew,

  thank you so much for your speedy reply.

I have tried your new setup.py file for pyhsmm-autoregressive plug in and it worked.  
I could then run all the three examples in "..\pyhsmm\plugins\pyhsmm-autoregressive-master\examples" successfully !

I tried to read across the change you made on the setup.py for the autoregressive plugin to the pyhsmm-slds and pyhsmm-factorial plugins too, but I was not as successful.

When I tried to run the pyhsmm-slds example files ("demo.py" and "meanfiled.py")  I got the ImportError: No module named pylds.states.

Similarly, when I tried to run the pyhsmm-factorial "example.py" file, I got the AttributeError: 'module' object has no attribute 'states'  

Please find below full trace for the errors mentioned above.

I'd be most grateful for your help in solving these issues.

Thanks again.

---

## C:\Users\Documents\python\pyhsmm\pyhsmm\plugins\pyhsmm-slds-master\examples>python demo.py                      Traceback (most recent call last):                                                                                                    File "demo.py", line 9, in <module>                                                                                                   from pyslds.models import WeakLimitStickyHDPHMMSLDS                                                                               File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pyslds\models.py", line 8, in <module>                               from states import HMMSLDSStatesPython, HMMSLDSStatesEigen, HSMMSLDSStatesPython, \                                               File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pyslds\states.py", line 12, in <module>                              from pylds.states import LDSStates                                                                                              ImportError: No module named pylds.states  

When running pyhsmm-factorial  EXAMPLE 
C:\Users\Documents\python\pyhsmm\pyhsmm\plugins\pyhsmm-factorial-master>python example.py                       Traceback (most recent call last):                                                                                                    File "example.py", line 9, in <module>                                                                                                import models                                                                                                                     File "C:\Users\Documents\python\pyhsmm\pyhsmm\plugins\pyhsmm-factorial-master\models.py", line 6, in <module>                from internals.states import FactorialStates,\                                                                                    File "C:\Users\Documents\python\pyhsmm\pyhsmm\plugins\pyhsmm-factorial-master\internals\states.py", line 151, in <module>                                                                                                                                        class FactorialComponentHSMMStates(pyhsmm.internals.states.HSMMStatesPython):                                                   AttributeError: 'module' object has no attribute 'states'

**Comment by andrwz** [comment]
Ok, I got through the first issue above, i.e. "ImportError: No module named pylds.states", just realized you wrote a separate module ("pylds"). 
I am having trouble in running the slds demo though (pyhsmm\plugins\pyhsmm-slds-master\examples>python demo.py ). the program seems to stall once it enters the re-sampling process and the graphics in the figure window goes a little crazy...was wondering if you had some clue as to what might be the cause?
Thanks

**Comment by mattjj** [comment]
Maybe try taking out all the graphics stuff and see if it runs; maybe that stuff doesn't play nicely with Windows.

I usually run the demo from one directory up, i.e. in the directory that contains the examples directory.

**Comment by andrwz** [comment]
Matthew,
Thanks for the suggestions.  I tried both, but no luck unfortunately .  
it looks to me the issue is with line n. 107
 "    model.resample_model()".  
the code seems to hang once it reaches that point.

**Comment by mattjj** [comment]
Can you step through in a debugger and find the precise place it hangs?

Are you able to run the pylds code?

**Comment by andrwz** [comment]
Matthew,
thanks again for the suggestions.

I am sorry I cannot yet answer your question on the precise place it hangs.  I have a bit of a learning curve here, both with python and with using a debugger..

I tried running the examples for  pylds .  “gibbs.py” runs ok, but I encountered the following errors when running “\pylds-master\examples\EM.py” and “\pylds-master\examples\meanfiled.py”respectively, could these be the problem?:

File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pylds\models.py", line 256, in M_step_dynamics_distn  
stats=(sum(s.E_dynamics_stats for s in self.states_list)))                                                            TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

File "C:\Users\Spaceman\Anaconda\envs\mscenv01\lib\site-packages\pylds\models.py", line 185, in meanfield_update_dynamics_distn
    stats=(sum(s.E_dynamics_stats for s in self.states_list)))
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

Full traces are below.

---------------------------------\pylds-master\examples\EM.py----------------------------------------------
C:\Users\Documents\python\pylds-master\examples>python EM.py  
Traceback (most recent call last):  
File "EM.py", line 51, in <module> 
likes = [update(model) for _ in progprint_xrange(50)]  
File "EM.py", line 46, in update                                                                                            model.EM_step()  
File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pylds\models.py", line 243, in EM_step                     self.M_step()                                                                                                           File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pylds\models.py", line 250, in M_step                      self.M_step_dynamics_distn()  
File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pylds\models.py", line 256, in M_step_dynamics_distn  
stats=(sum(s.E_dynamics_stats for s in self.states_list)))                                                            TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

--------------------------------\pylds-master\examples\meanfiled.py--------------------------------------------

C:\Users\Documents\python\pylds-master\examples>python meanfield.py
.........................  [  25/100,    0.05sec avg, ETA 3.74 ]
.........................  [  50/100,    0.05sec avg, ETA 2.44 ]
.........................  [  75/100,    0.05sec avg, ETA 1.25 ]
.........................  [ 100/100,    0.05sec avg, ETA 0.00 ]

   0.05sec avg, 5.08 total

Traceback (most recent call last):
  File "meanfield.py", line 53, in <module>
    vlbs = [update(model) for _ in progprint_xrange(50)]
  File "meanfield.py", line 46, in update
    return model.meanfield_coordinate_descent_step()
  File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pylds\models.py", line 170, in meanfield_coordinate_descent_step
    self.meanfield_update_parameters()
  File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pylds\models.py", line 180, in meanfield_update_parameters
    self.meanfield_update_dynamics_distn()
  File "C:\Users\Anaconda\envs\mscenv01\lib\site-packages\pylds\models.py", line 185, in meanfield_update_dynamics_distn
    stats=(sum(s.E_dynamics_stats for s in self.states_list)))
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

**Comment by mattjj** [comment]
That's just a bug (I wonder when I broke it...). Fix incoming.

**Comment by mattjj** [comment]
I pushed a fix in 8b78025 of pylds but I can't test it because I'm rebuilding some software on my machine at the moment.

**Comment by andrwz** [comment]
Thank you for your reply. I have implemented the change in 8b78025 of pylds and can confirm the issues with running “\pylds-master\examples\EM.py” and “\pylds-master\examples\meanfield.py”reported above have been resolved.  Thanks for fixing this. The issue with pyhsmm-slds " model.resample_model()" still persists and still trying to figure that out.

**Comment by mattjj** [comment]
We've changed a lot about pyslds since this issue, so I'm going to close it.
