### ISSUE TITLE
missing dependency 'hips'

### ISSUE THREAD

**Issue by nfoti** [mattjj/pyhsmm-slds#10]
The script `examples/slds_example_figure.py` requires the `hips` module. This doesn't seem to be a publicly available module from `conda` or `pip`. Could either i) instructions for installing it be included in the README or ii) could the functionality be replaced with publicly available packages?

**Comment by slinderman** [comment]
Good call.  I've removed that dependency in https://github.com/mattjj/pyslds/commit/a341192adbb7be65f26a0ba1802e80fc014e0261.  Let me know if it works.
