### ISSUE TITLE
Meanfield with DefaultWeakLimitStickyHDPSLDS not implemented

### ISSUE THREAD

**Issue by DanteArucard** [mattjj/pyhsmm-slds#17]
Dear Matthew,

I found that DefaultWeakLimitStickyHDPSLDS does not support  meanfield inference, I think you wrote something about that here in this [comment](https://github.com/mattjj/pyhsmm/issues/48#issuecomment-290924471). 
In fact `WeakLimitStickyHDPHMMTransitions` does not implement the meanfield update.

I was still trying to extract the models after training (as other attempted [
@eliotmoss ](https://github.com/mattjj/pyslds/issues/13),  [@mg10011 ](https://github.com/mattjj/pyhsmm/issues/62) ,and [me](https://github.com/mattjj/pyslds/issues/14))

I wanted to try StickyHDPSLDS because with normal HDPSLDS i get high errors (specially with meanfield) and gibbs should be affected by the label switching issue. (Or it is not?)
I thought that high errors could be caused by excessive switching frequency

**Comment by AaronIntro** [comment]
Dear Matthew,
 
I also found the WeakLimitHDPHSMM does not support meanfield_sgdstep. In  my project I found the resampling method could not convergence for a particular day (e.g. the last day of time series). The latent state is switching between two different states ( [0,1,2] three states for e.g.). I think the SVI method may be suitable, however it could not work within the error as follows,

AttributeError: 'WeakLimitHDPHSMMTransitions' object has no attribute 'exp_expected_log_trans_matrix'

**Comment by slinderman** [comment]
Hi Aaron,
The `WeakLimit*` models only support Gibbs sampling.  Only the regular `HMMSLDS` supports mean field variational inference.   Can you try that instead?  For what it's worth, SVI requires some tuning of minibatch sizes and learning rates, and it's not a priori clear to me that it will be more effective that Gibbs in this setting (though still worth a shot!).  It could be that the Gibbs sampler is reflecting genuine uncertainty about the latent state in the last day.   

@mattjj I opened https://github.com/mattjj/pyhsmm/issues/78 (and assigned to myself) as a result of this issue. I don't think WeakLimit models should expose mean field interfaces. 

--Scott
