### ISSUE TITLE
model.resample_model() hits an assert X.shape[0] == T

### ISSUE THREAD

**Issue by shiwanlin** [mattjj/pyhsmm-slds#18]
I tried to run the sample test as below (cut and pasted from the readme.md).

When running model.reasample_model(), it runs into an assert exception, 
   assert X.shape[0] == T, 
in lds_messages_interface.py in _ensure_ndim(X, T, ndim) (see trace below).

When the assertion throws, X.shape[0]=1999 and T=2000.

pyhsmm and pypolyagamma work by themselves.

Not sure what is the problem. Help appreciated!!!

```python
#=============================================================
# Code
# =============================================================
%matplotlib notebook
import numpy as np
import numpy.random as npr
from pyslds.models import DefaultSLDS
########################################################
K = 5               # Number of discrete latent states
D_obs = 1           # Observed data dimension
D_latent = 2        # Latent state dimension
D_input = 0         # Exogenous input dimension
T = 2000            # Number of time steps to simulate

true_model = DefaultSLDS(K, D_obs, D_latent, D_input)
inputs = npr.randn(T, D_input)
y, x, z = true_model.generate(T, inputs=inputs)

# Compute the log likelihood of the data with the true params
true_ll = true_model.log_likelihood() 
########################################################
# Create a separate model and add the observed data
test_model = DefaultSLDS(K, D_obs, D_latent, D_input)
test_model.add_data(y)

print("y.shape =", y.shape)

# Run the Gibbs sampler
N_samples = 1000
def update(model):
    model.resample_model()
    return model.log_likelihood()

print(update(test_model))

#lls = [update(test_model) for _ in range(N_samples)]
```
```
#=============================================================
# Console and Trace
#=============================================================
y.shape = (2000, 1)
ndim =  3
X.shape =  (1999, 2, 2)
T =  2000
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-9a6a6754ad10> in <module>()
     32     return model.log_likelihood()
     33 
---> 34 print(update(test_model))
     35 
     36 #lls = [update(test_model) for _ in range(N_samples)]

<ipython-input-7-9a6a6754ad10> in update(model)
     29 N_samples = 1000
     30 def update(model):
---> 31     model.resample_model()
     32     return model.log_likelihood()
     33 

C:\devtools\Anaconda3\lib\site-packages\pyhsmm-0.1.6-py3.5-win-amd64.egg\pyhsmm\models.py in resample_model(self, num_procs)
    440     def resample_model(self,num_procs=0):
    441         self.resample_parameters()
--> 442         self.resample_states(num_procs=num_procs)
    443 
    444     @line_profiled

C:\devtools\Anaconda3\lib\site-packages\pyhsmm-0.1.6-py3.5-win-amd64.egg\pyhsmm\models.py in resample_states(self, num_procs)
    465         if num_procs == 0:
    466             for s in self.states_list:
--> 467                 s.resample()
    468         else:
    469             self._joblib_resample_states(self.states_list,num_procs)

C:\devtools\Anaconda3\lib\site-packages\pyslds\states.py in resample(self, niter)
    380         for itr in range(niter):
    381             self.resample_discrete_states()
--> 382             self.resample_gaussian_states()
    383 
    384     def _init_gibbs_from_mf(self):

C:\devtools\Anaconda3\lib\site-packages\pyslds\states.py in resample_gaussian_states(self)
    391         self._aBl = None  # clear any caching
    392         self._gaussian_normalizer, self.gaussian_states = \
--> 393             info_sample(*self.info_params)
    394 
    395 

C:\devtools\Anaconda3\lib\site-packages\pylds\lds_messages_interface.py in wrapped(*args, **kwargs)
     66     @wraps(func)
     67     def wrapped(*args, **kwargs):
---> 68         return func(*check(*args,**kwargs))
     69     return wrapped
     70 

C:\devtools\Anaconda3\lib\site-packages\pylds\lds_messages_interface.py in _info_argcheck(J_init, h_init, log_Z_init, J_pair_11, J_pair_21, J_pair_22, h_pair_1, h_pair_2, log_Z_pair, J_node, h_node, log_Z_node)
     96     J_pair_11, J_pair_21, J_pair_22, J_node = \
     97         map(partial(_ensure_ndim, T=T, ndim=3),
---> 98             [J_pair_11, J_pair_21, J_pair_22, J_node])
     99     h_pair_1, h_pair_2 = \
    100         map(partial(_ensure_ndim, T=T, ndim=2),

C:\devtools\Anaconda3\lib\site-packages\pylds\lds_messages_interface.py in _ensure_ndim(X, T, ndim)
     25         print('X.shape = ',  X.shape)
     26         print('T = ', T)
---> 27         assert X.shape[0] == T
     28         return X
     29     else:

AssertionError: 
```

**Comment by shiwanlin** [comment]
Also ran the simple_example.py and got the same assertion this time: with 999 != 1000, the X zero dimension is also 1 less than T :-(

ndim =  3
X.shape =  (999, 2, 2)
T =  1000

**Comment by shiwanlin** [comment]
> c:\devtools\anaconda3\lib\site-packages\pyslds\states.py(393)resample_gaussian_states()
    391         self._aBl = None  # clear any caching
    392         self._gaussian_normalizer, self.gaussian_states = \
--> 393             info_sample(*self.info_params)
    394 
    395 

ipdb> print(self.info_params[0].shape)
(2, 2)
ipdb> print(self.info_params[1].shape)
(2,)
ipdb> print(self.info_params[2].shape)
()
ipdb> print(self.info_params[3].shape)
(1999, 2, 2)
ipdb> print(self.info_params[4].shape)
(1999, 2, 2)
ipdb> print(self.info_params[5].shape)
(1999, 2, 2)
ipdb> print(self.info_params[6].shape)
(1999, 2)
ipdb> print(self.info_params[7].shape)
(1999, 2)
ipdb> print(self.info_params[8].shape)
(1999,)
ipdb> print(self.info_params[9].shape)
(2000, 2, 2)
ipdb> print(self.info_params[10].shape)
(2000, 2)
ipdb> print(self.info_params[11].shape)
(2000,)

**Comment by shiwanlin** [comment]
The problem goes away after updated numpy along with a few other packages :-( :-)

    astropy:      1.2.1-np111py35_0              --> 2.0.1-np113py35_1  conda-forge
    bottleneck:   1.1.0-np111py35_0              --> 1.2.0-np113py35_0  conda-forge
    conda:        4.3.22-py35_0      conda-forge --> 4.3.23-py35_0      conda-forge
    h5py:         2.6.0-np111py35_2              --> 2.7.0-np113py35_0
    libpng:       1.6.22-vc14_0                  [vc14] --> 1.6.28-vc14_1      conda-forge [vc14]
    llvmlite:     0.14.0-py35_0                  --> 0.19.0-py35_0
    matplotlib:   1.5.3-np111py35_1              --> 2.0.2-np113py35_0
    mkl:          11.3.3-1                       --> 2017.0.3-0
    numba:        0.29.0-np111py35_0             --> 0.34.0-np113py35_0
    numexpr:      2.6.1-np111py35_1              --> 2.6.2-np113py35_0  conda-forge
    numpy:        1.11.2-py35_0                  --> 1.13.1-py35_0
    pandas:       0.19.1-np111py35_0             --> 0.20.3-py35_1      conda-forge
    pytables:     3.2.2-np111py35_4              --> 3.2.2-np113py35_4
    scikit-image: 0.12.3-np111py35_1             --> 0.13.0-py35_1      conda-forge
    scikit-learn: 0.18.1-np111py35_0             --> 0.19.0-np113py35_0
    scipy:        0.18.1-np111py35_0             --> 0.19.1-np113py35_0
    statsmodels:  0.6.1-np111py35_1              --> 0.8.0-np113py35_0  conda-forge

**Comment by slinderman** [comment]
Hi Shi-Wan,
Sorry for the delayed response. I believe this stemmed from a breaking change I made in pylds: the latest code requires the dynamics params to be length T-1 instead of length T. You probably had to update both pylds and pyslds to get it to work. We will push to pypi soon.
Best,
Scott
