### ISSUE TITLE
slds_example_figure.py

### ISSUE THREAD

**Issue by gulsunde** [mattjj/pyhsmm-slds#19]
Traceback (most recent call last):
  File "slds_example_figure.py", line 235, in <module>
    draw_slds_figure(z,x,y,slds)
TypeError: draw_slds_figure() takes exactly 3 arguments (4 given)

I just tried to run the example.

**Comment by slinderman** [comment]
Should be fixed in 
 https://github.com/mattjj/pyslds/commit/13e55ef1a74930d2c65dcd45eee27f107ad9b285
