### ISSUE TITLE
 Examples give error "Exception: Must specify gaussian states and discrete states.."

### ISSUE THREAD

**Issue by ascakmak** [mattjj/pyhsmm-slds#21]
Hello,

I am having following error when I try to run nearly all of your example codes (except demo.py, which gives error described in #20 ).

> Exception: Must specify gaussian states and discrete states if you want to initialize with given latent states.

I am using a mac with basic anaconda installed. I installed your repo by git clone-ing and then "sudo pip install -e". I can run your 'pylds' repo example without problem.

Do you know why this could be? Maybe examples were not updated after a few commits? I am looking forward to using this repo, thanks a lot for your time!

**Comment by ascakmak** [comment]
> Traceback (most recent call last):
  File "simple_demo.py", line 68, in <module>
    y, x, _ = true_model.generate(T, inputs=inputs, stateseq=z)
  File "/Users/ascakmak/repos/pyslds/pyslds/models.py", line 37, in generate
    s = self._states_class(model=self, T=T, initialize_from_prior=True, **kwargs)
  File "/Users/ascakmak/repos/pyslds/pyslds/states.py", line 876, in __init__
    super(_SLDSStatesMaskedData, self).__init__(model, data=data, **kwargs)
  File "/Users/ascakmak/repos/pyslds/pyslds/states.py", line 464, in __init__
    super(_SLDSStatesVBEM, self).__init__(model, **kwargs)
  File "/Users/ascakmak/repos/pyslds/pyslds/states.py", line 667, in __init__
    super(_SLDSStatesMeanField, self).__init__(model, **kwargs)
  File "/Users/ascakmak/repos/pyslds/pyslds/states.py", line 32, in __init__
    raise Exception("Must specify gaussian states and discrete states if "
Exception: Must specify gaussian states and discrete states if you want to initialize with given latent states.

**Comment by slinderman** [comment]
Thanks for raising this.  I believe I've fixed it in a recent commit.
