### ISSUE TITLE
how to properly satisfy pylds dependency

### ISSUE THREAD

**Issue by clemense** [mattjj/pyhsmm-slds#4]
Hi,
How do I properly satisfy the pylds dependency?

If I do it using 'pip install pylds' and run demo.py I get:

AttributeError: type object 'LDSStates' has no attribute '_info_extra_loglike_terms'

If I checkout the current version from the GIT repository I end up with:

ImportError: /home/someuser/code/pylds/pylds/lds_messages.so: undefined symbol: PyFPE_jbuf

Thanks!

**Comment by mattjj** [comment]
Looks like a build error. Can you try cloning the master pylds branch from github, like this?

```
cd ~/code
git clone https://github.com/mattjj/pylds.git
cd pylds
pip install -e .
```

You might also want to update cython, numpy, and scipy.

**Comment by clemense** [comment]
Hmmm, no luck.
I did the `pip install -e .` from the github master branch and it finally states:

```
Successfully installed pylds-0.0.2
```

But when running examples/meanfield.py or examples/demo.py I still get:

```
File "/home/someuser/code/pylds/pylds/states.py", line 7, in <module>
from lds_messages_interface import kalman_filter, filter_and_sample, E_step, \
  File "/home/someuser/code/pylds/pylds/lds_messages_interface.py", line 10, in <module>
from lds_messages import \
ImportError: /home/someuser/code/pylds/pylds/lds_messages.so: undefined symbol: PyFPE_jbuf
```

I have numpy version 1.11.1, cython 0.24.1, scipy 0.17.1.

**Comment by clemense** [comment]
Alright, sorry my mistake. I forgot to explicitly remove all the old files from the previous build.
Now, one example works.

**Comment by mattjj** [comment]
Great! Glad you got it sorted out, and thanks for updating here.
